import * as XLSX from 'xlsx';

/**
 * Export matrix data to Excel file
 * @param {Object} matrixData - The matrix data from the backend
 * @param {string} summary - Summary text to include
 * @param {string} recommendations - Recommendations text to include
 * @param {string} filename - Optional filename (defaults to 'testmind-matrix.xlsx')
 */
export const exportToExcel = (matrixData, summary = '', recommendations = '', filename = 'testmind-matrix.xlsx') => {
  const workbook = XLSX.utils.book_new();
  
  // Create matrix worksheet
  const transitions = Object.keys(matrixData);
  const personas = new Set();
  
  transitions.forEach(transition => {
    Object.keys(matrixData[transition]).forEach(persona => {
      personas.add(persona);
    });
  });
  
  const personaArray = Array.from(personas);
  
  // Create matrix data for Excel
  const matrixRows = [];
  
  // Header row
  const headerRow = ['Transition', ...personaArray];
  matrixRows.push(headerRow);
  
  // Data rows
  transitions.forEach(transition => {
    const row = [transition];
    personaArray.forEach(persona => {
      const data = matrixData[transition][persona];
      const status = data?.status || 'Unknown';
      const id = data?.id || '';
      row.push(`${status}${id ? ` (${id})` : ''}`);
    });
    matrixRows.push(row);
  });
  
  // Create matrix worksheet
  const matrixWorksheet = XLSX.utils.aoa_to_sheet(matrixRows);
  XLSX.utils.book_append_sheet(workbook, matrixWorksheet, 'Test Matrix');
  
  // Create summary worksheet
  if (summary || recommendations) {
    const summaryData = [];
    
    if (summary) {
      summaryData.push(['Summary']);
      summaryData.push([summary]);
      summaryData.push([]); // Empty row
    }
    
    if (recommendations) {
      summaryData.push(['Recommendations']);
      summaryData.push([recommendations]);
    }
    
    const summaryWorksheet = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(workbook, summaryWorksheet, 'Summary');
  }
  
  // Create metadata worksheet
  const metadata = [
    ['Generated by', 'TestMind AI'],
    ['Generated on', new Date().toLocaleString()],
    ['Total Transitions', transitions.length],
    ['Total Personas', personaArray.length],
    ['Total Test Cases', transitions.length * personaArray.length],
    [],
    ['Transitions'],
    ...transitions.map(t => [t]),
    [],
    ['Personas'],
    ...personaArray.map(p => [p])
  ];
  
  const metadataWorksheet = XLSX.utils.aoa_to_sheet(metadata);
  XLSX.utils.book_append_sheet(workbook, metadataWorksheet, 'Metadata');
  
  // Auto-size columns for matrix worksheet
  const matrixRange = XLSX.utils.decode_range(matrixWorksheet['!ref']);
  for (let col = 0; col <= matrixRange.e.c; col++) {
    const colLetter = XLSX.utils.encode_col(col);
    matrixWorksheet[`${colLetter}1`] = { 
      ...matrixWorksheet[`${colLetter}1`],
      s: { font: { bold: true } }
    };
  }
  
  // Export the file
  XLSX.writeFile(workbook, filename);
};

/**
 * Export conversation history to Excel
 * @param {Array} messages - Array of message objects
 * @param {string} filename - Optional filename (defaults to 'testmind-conversation.xlsx')
 */
export const exportConversationToExcel = (messages, filename = 'testmind-conversation.xlsx') => {
  const workbook = XLSX.utils.book_new();
  
  const conversationData = [
    ['Timestamp', 'Sender', 'Type', 'Content']
  ];
  
  messages.forEach(message => {
    let content = '';
    if (message.type === 'bot' && message.content.status === 'success') {
      content = `Summary: ${message.content.summary || 'N/A'}\n\nMatrix Data: ${JSON.stringify(message.content.matrix_data, null, 2)}`;
    } else if (message.type === 'bot' && message.content.status === 'conversation') {
      content = message.content.response || 'N/A';
    } else {
      content = message.content;
    }
    
    conversationData.push([
      message.timestamp,
      message.type === 'bot' ? 'TestMind AI' : 'User',
      message.type,
      content
    ]);
  });
  
  const worksheet = XLSX.utils.aoa_to_sheet(conversationData);
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Conversation');
  
  // Auto-size columns
  const range = XLSX.utils.decode_range(worksheet['!ref']);
  for (let col = 0; col <= range.e.c; col++) {
    const colLetter = XLSX.utils.encode_col(col);
    worksheet[`${colLetter}1`] = { 
      ...worksheet[`${colLetter}1`],
      s: { font: { bold: true } }
    };
  }
  
  XLSX.writeFile(workbook, filename);
}; 